### ISSUE TITLE
(julia) It should remove the old version on updating

### ISSUE THREAD

**Issue by aminya** [chocolatey-community/chocolatey-packages#1548]
The Julia package does not remove the old version on updating.
https://chocolatey.org/packages/Julia
https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/julia

## Expected Behavior
Remove the old version

## Current Behavior

Does not remove

## Your Environment

* Package Version used: 1.5.2
* Operating System and version: win 10

**Comment by AdmiringWorm** [comment]
TBH, I am a bit hesitant to add any uninstallation of older versions.
We currently do not have any way to know which version was previously installed by the package, and since the installer allows multiple installations, we could mistakenly remove a version that was intentionally installed side-by-side.

Anyhow, I will still add this as an `Up for Grabs`  item.

**Comment by aminya** [comment]
This is inconsistent with what you have in the documentation. Calling uninstall for Julia does not work, which is very strange for a package that is managed by the core team.

You must be able to use a glob pattern to find all the Julia installations. Also, keeping track of the installed apps should not be hard.

Note that all the Julia instances share the `~/.julia` path. Upon uninstallation, you should not remove that folder. Just running the official uninstall.exe is enough.

**Comment by AdmiringWorm** [comment]
> This is inconsistent with what you have in the documentation. Calling uninstall for Julia does not work, which is very strange for a package that is managed by the core team.

The uninstall works as intended, unfortunately it only works if it can find a single installation of the program (at least the script, the auto-uninstaller should work in other cases, but that may not always be completely silent).

> The Julia installations appear in the program list. You should also be able to use a glob pattern to find all the Julia installations. Also, keeping track of the installed apps should not be hard.

The problem isn't finding the installations, nor keeping track of them (in general).
The problem is that we are not able to detect in the package whether multiple installations is intentional, or if it is an upgrade from a specific version.

**Comment by aminya** [comment]
Unstale

**Comment by pauby** [comment]
What is the way forward with this one? There has been no update since October.

**Comment by AdmiringWorm** [comment]
@pauby there hasn't been any work on this issue AFAIK.

**Comment by pauby** [comment]
@AdmiringWorm Is there anything that we intend to do here? 'No' is a valid answer.

**Comment by AdmiringWorm** [comment]
@pauby I can not speak for anyone else, however, I do not currently have any plans of doing anything regarding this issue (this is also the main reason it is up for grabs by the community).

**Comment by pauby** [comment]
Thanks @AdmiringWorm 

@aminya This isn't something the Community Core Team would work on, so it's been left open for others to pick up. Might be a good issue for you to pick up?
