### ISSUE TITLE
(kitty) Configuration is not possible 

### ISSUE THREAD

**Issue by malcook** [chocolatey-community/chocolatey-packages#1629]
Supposedly, in kitty [You can open the config file within kitty by pressing ctrl\+shift\+f2](https://sw.kovidgoyal.net/kitty/conf.html#shortcut-kitty.Edit-config-file)

but when I try I am alerted: Error Unable to find requested file. I can not otherwise find kitty's config file.

--- Provide a general summary of the issue in the Title above, prefixed with (packageName) -->

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
hmm, may be a case for defaulting to the `Get-ChocolateyToolsFolder` location, instead of the package tools directory.

This way it should still have write permissions when not running as an admin.
TBH, I am not really familiar with `kitty` so I am not sure if it makes sense to have it located in an insecure location (a place not locked down to administrators).
I'll still add this as an enhancement request

**Comment by malcook** [comment]
FWIW: I tried setting environment variable KITTY_CONFIG_DIRECTORY to point to a custom config but continue to get the reported error.
