### ISSUE TITLE
(ffmpeg) Installation Error (I/O conflicts ?)

### ISSUE THREAD

**Issue by yuichi-github** [chocolatey-community/chocolatey-packages#1652]
An error frequently occurs while the ffmpeg package installation (4.3.2 -> 4.4).
The error occurs on some machines and not on others.
( [The FFmpeg Thread](https://community.chocolatey.org/packages/ffmpeg#comment-5380268449) )

```
mpeg 4.4... 99% Progress: Downloading ffmpeg 4.4... 100%
ffmpeg v4.4 [Approved] ffmpeg package files upgrade completed. Performing other installation steps. Extracting 64-bit C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-release-essentials.7z to C:\ProgramData\chocolatey\lib\ffmpeg\tools... C:\ProgramData\chocolatey\lib\ffmpeg\tools
ERROR
: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to
Stop: Access to the path 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-4.4-essentials_build' is denied. The upgrade of ffmpeg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1'.
See log for details. Chocolatey upgraded 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures - ffmpeg (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1'.
See log for details.
```

## Expected Behavior
An installation succeeds.

## Current Behavior
See above.

## Possible Solution
The part of the code ’tools\chocolateyInstall.ps1’ is below.

```
Get-ChildItem $toolsPath\* | Where-Object { $_.PSISContainer } | Remove-Item -Recurse -Force #remove older package dirs
Get-ChocolateyUnzip @packageArgs
Remove-Item $toolsPath\*.7z -ea 0

Move-Item $toolsPath\ffmpeg-* $toolsPath\ffmpeg
```

I guess the problem is caused by the line starts with 'Move-Item'.
Some I/O conflicts may occur by the commad.
Inserting a short sleep may be effective.

## Steps to Reproduce (for bugs)
`choco install ffmpeg -y`

## Context
I would like to install ffmpeg to various test servers by CLI.

## Your Environment

* Package Version used: ffmpeg 4.4
* Operating System and version: Windows Server 2012 R2 / Windows Server 2019
* Chocolatey version: 0.10.5
* Install/uninstall gist: N/A

**Comment by AdmiringWorm** [comment]
hmm, this is something that is difficult to reproduce.
I have not seen this happen myself, nor have I been able to reproduce the error.

My thought is that there may be an issue with a anti-virus software installed in the environment that is locking the folder (or a file in the folder) which causes the moving of the folder to fail.

**Comment by MaxwellDAssistek** [comment]
I have this occurring as well. Same deal. Running Windows 10 x64.

```
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Extracting 64-bit C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-release-essentials.7z to C:\ProgramData\chocolatey\lib\ffmpeg\tools...
C:\ProgramData\chocolatey\lib\ffmpeg\tools
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Access to the path 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-4.4-essentials_build' is denied.
The install of ffmpeg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by AdmiringWorm** [comment]
@MaxwellDAssistek long shot, but do you happen to still have the installation log for the installation of the package?

Did you install the package while running as an administrator?
Was ffmpeg already running some decoding/encoding when the package was installing?

**Comment by MaxwellDAssistek** [comment]
@AdmiringWorm Thanks for the reply. I actually do still have the log. Here is the part of the log that seems to do with the operation of installing ffmpeg: https://gist.github.com/MaxwellDAssistek/3b341ef4f5ce019bd65437631e8ff3ab

I did install running as admin, and there was no other install of ffmpeg at all on the system as chocolatey was my first stop at trying to get ffmpeg.

I cannot replicate the issue anymore though.

**Comment by AdmiringWorm** [comment]
Hmm, as I was afraid of. The log doesn't really contain any more information than we already knew about.

As I mentioned before, I believe this issue is caused by something locking the folder after it was extracted.
This could be an anti-virus, 7zip itself, or something completely else (I believe most likely the anti-virus).

While I can not reproduce the issue, I'll have a look at some point to retry the renaming the folder during installation a few times (while pausing for a few seconds between each try) and get that that added to the package.

**Comment by TommeTao** [comment]
I ran into the same issue on my business machine (Windows 10) and the cause was indeed the antivirus software, as suspected by @AdmiringWorm:

> As I mentioned before, I believe this issue is caused by something locking the folder after it was extracted. This could be an anti-virus, 7zip itself, or something completely else (I believe most likely the anti-virus).

More specifically, our company is running McAfee Endpoint Security 10.7.

I was able to solve the issue and install FFmpeg (`ffmpeg-full`) via Chocolatey by disabling **On-Access Scan** (under **Settings** -> **Threat Prevention**):

<img src="https://user-images.githubusercontent.com/95080284/153954769-80d72f38-3fce-4b9b-b209-c05075f9d286.png" width=80% height=80%>

However, I am wondering what is causing this issue for FFmpeg!? I have about 20 Chocolatey packages installed and FFmpeg is the first one where I have encountered such a problem with McAfee.

**Comment by AdmiringWorm** [comment]
> However, I am wondering what is causing this issue for FFmpeg!? I have about 20 Chocolatey packages installed and FFmpeg is the first one where I have encountered such a problem with McAfee.

This is just speculation on my part, but I would believe it is either due to the size of the archive itself, or more likely due to the number of files located inside the archive.
The more files there are, the longer it usually takes for anti-viruses to scan all of the files, especially when they are extracted from archives (or copied from a different drive as well to the same location).

**Comment by AdmiringWorm** [comment]
A new fix version for the ffmpeg and ffmpeg-full package is queued to be pushed to Chocolatey Community Repository with some changes to retry the renaming of the directory that fails in this issue.

As I had mentioned before, I still have not been able to reproduce the problem, so do let me know in this issue whether the issue persists or not once the new fix version is approved.

**Comment by yuichi-github** [comment]
I tried it with v5.0.1.20220408 in the same context and confirmed that the problem has been fixed.
I appreciate it very much!
