### ISSUE TITLE
(TotalCommander) v10 is not published

### ISSUE THREAD

**Issue by CWempe** [chocolatey-community/chocolatey-packages#1708]
A few month ago v10 of Total Commander was officially released.
https://www.ghisler.com/whatsnew.htm

According to [this](https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/04535ea4afd51bc42827c5c2a029421e3c5de192#diff-16af7040a09071315e8257819bfbcc7c1f67cad353f7e48bbc33f6bba439ddfd) commit, somebody tried(?) to update the chocolatey package.
But somehow the [package](https://community.chocolatey.org/packages/TotalCommander#versionhistory) is still at v9.51.

Can anybody fix this?
There has been no response to the Disqus comments.

Thanks.

**Comment by majkinetor** [comment]
https://community.chocolatey.org/packages/totalcommander/10.0

Failed verifcation:

https://gist.github.com/choco-bot/0fce3f8f2b217175ed63c94611b16cfa#file-install-txt-L1000

**Comment by majkinetor** [comment]
TC10 changed the installer and that is the reason it fails:

* https://www.ghisler.ch/wiki/index.php?title=How_to_make_installation_fully_automatic%3F

**Comment by majkinetor** [comment]
I fixed it using new installer features, but it failed validation because of the method used (env vars):

- https://community.chocolatey.org/packages/TotalCommander/10.0.0.20210903

The reason for this kind of code is that there is a bug in choco:

* https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1#L359

In `"$silentArgs $additionalInstallArgs"` space is added to silent args which makes TC installation fail to set up folder so I had to use this as a workaround:

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/0a7332f2ad972850d197d5f7b706eb904c45b314/automatic/totalcommander/tools/chocolateyInstall.ps1#L8-L9 

I can obfuscate this line to not trigger the veriifer but its bet if bug can be fixed (/cc @gep13 @ferventcoder ) or at least tool excluded from validation. I am quite surprised that nobody else detected it, but tools don't usually consider command line whitespace as relevant.

**Comment by majkinetor** [comment]
Thx @TheCakeIsNaOH. Looks like we might have the same problem on next version ?

**Comment by TheCakeIsNaOH** [comment]
Yup, every individual version would have to be exempted until either this issue is fixed (and released) or until another workaround that does not trigger the validator is found.

**Comment by gep13** [comment]
@majkinetor apologies, I had it on my list to come back to you on this one, but looks like it fell off my radar 😢 

It currently isn't possible to provide a permanent exemption from package-validator (this is only possible with package-verifier) but this is by-design, and there aren't any plans to change that.

While we wait until the bug is addressed in Chocolatey (which should hopefully be included in the next release) which would prevent the need for the current workaround, @TheCakeIsNaOH has suggested that we get you added as a maintainer on the TotalCommander package.  That way, if/when you notice that it has failed package-validator, you can request an exemption from one of the moderators.

I am going to go ahead and add you as a maintainer on the package, but if this is not something that you want, let us know, and we can cancel the request to get you added.

**Comment by AdmiringWorm** [comment]
I am looking over a few old issues, and noticed this issue do not seem to be relevant anymore.

As the 10.x version of totalcommander is available on the Chocolatey Community Repository, I'll close this issue now.
