### ISSUE TITLE
(360tse) Version 8.8.0.1119 advertises connection with BitDefender and Avira.

### ISSUE THREAD

**Issue by wotacs** [chocolatey-community/chocolatey-packages#1720]
The description for the above package claims a connection with BitDefender and Avira software. The package website makes no mention of this connection. The package in the Chocolatey repository was last updated in 2018, which may make it badly out-of-date, the "false advertising" notwithstanding.

## Expected Behavior

That the description omits the words Avira and BitDefender to correctly reflect that there is no relationship between these 3 vendors.

## Current Behavior
Searching for BitDefender returns additional unrelated results (360 Total Security and 360 Total Security Essentials)

## Possible Solution

1) Edit the description to remove the words Avira and BitDefender 
2) Remove the out-of-date package 

## Steps to Reproduce (for bugs)

1. Search for avira or bitdefender in the main repository
2. Note that 360tse Version 8.8.0.1119 is among the returned results.

## Context

360tse package appears to claim a connection with both BitDefender and Avira, The 360ts website makes no mention of this connection. Searches for Avira and BitDefender return unrelated results.

## Your Environment

* Package Version used:  Not installed.
* Operating System and version: Windows 10 Pro 21H2 19043.1237
* Chocolatey version: 0.11.2
* Install/uninstall gist: Not sure what this is asking.

**Comment by pauby** [comment]
@wotacs I appreciate you raising this off the back of the email discussion.

**Comment by RedBaron2** [comment]
The 360 Total Security Essential application has been discontinued since 2019 and had also been removed from AU checking around the same time.

@wotacs 
I have to wonder why you are asking about an application that has been discontinued for almost 2 years. Since people don't know history. Allow me please to link to this  [page](https://web.archive.org/web/20190529084331/http://www.360totalsecurity.com/en/features/360-total-security-essential/)
This is how the page looked back in the day. The first paragraph lists the multi engine approach that 360 Total Security Essential used.
The references that are made about Avira and BitDefender not being on the current 360 Total Security page are correct, but both packages 360ts & 360tse had at one time used these additional scanning databases in their applications. The 360 Total Security application has undergone recent updates and removed its ability to use the BitDefender and Avira databases. The description for the 360ts package should probably be updated to mention this change. Please, feel free to submit a PR if you feel so inclined.
Thank you for the feedback.

**Comment by wotacs** [comment]
I raised this issue because the product is so out-of-date and yet it comes up in a search for two other well-known and current AV products. It may be time to totally remove it from the repository, or mark it prominently as Out-Of-Date.

**Comment by RedBaron2** [comment]
Please, @wotacs next time edit your replies for charity.

The process for updating a package as outdated is mentioned on the package page. This usually requires submitting a PR that changes the metadata to outdated/discontinued.

@majkinetor or @pauby can help you with this process. I will second the vote to move the 360tse package as outdated.

Thanks for the reply.

**Comment by wotacs** [comment]
I apologise for any confusion caused, @RedBaron2, This is my first experience with GitHub Issue Tracking. I'd be happy to fix any mistakes made, if I could get a better idea where I have erred.  My uneducated assumption would be that I should have pruned the incoming email text - happy to go back in this email chain and do that, if this is my main failure. 

I'll ask a bit of leeway while I learn (as fast as I can) how to interact here in the best possible manner.

**Comment by pauby** [comment]
If the final release of the package is on the community repository then my suggestion would be to submit one last version, mark it as EOL, change the description to remove the lines that @wotacs mentioned and also to update the description to confirm it's EOL.

If the package has been [deprecated](https://docs.chocolatey.org/en-us/community-repository/maintainers/deprecate-a-chocolatey-package#mainContent), then follow that process instead.

**Comment by pauby** [comment]
As there has been no update on this issue and nobody has picked it up, I'm going to go ahead and close it. We can always re-open it if necessary.
