### ISSUE TITLE
(googlechrome) SessionNotCreatedException: Message: session not created

### ISSUE THREAD

**Issue by elveera0491** [chocolatey-community/chocolatey-packages#1722]
There seems to be an issue with the current googlechrome package. When you try running tests on a remote VM from Jenkins, it fails with the following error: SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
(Session info: chrome=93.0.4577.82)
It works perfectly with older version (v92 and older). Trying to run tests with GUI and not headless mode.

The issue seems to have passed on to the new version of chrome(94.0.4606.61) and chromedriver(94.0.4606.610). Our tests passed successfully before the chocolatey version for chrome on Wednesday, September 1, 2021.

**Comment by ekbharani** [comment]
We were facing the same issue until a couple of days back. All our batch files were scheduled on windows task scheduler and they would inturn trigger robot framework scripts. But after this upgrade, all the taks would run and fail with this error. What we did was to install another software called "system scheduler" and scheduled all our tasks on them. Been a day and not seen any sessionnotfound error so far. Hoping that Chrome gives us an update sooner.

**Comment by pauby** [comment]
Is this an issue with the package or with Google Chrome?

**Comment by ekbharani** [comment]
Thanks for bringing this up Paul. I am guessing that this is because of chrome. But let's wait for their response.Sent from my Galaxy
-------- Original message --------From: Paul Broadwith ***@***.***> Date: 2021-10-04  11:51 a.m.  (GMT-05:00) To: chocolatey-community/chocolatey-coreteampackages ***@***.***> Cc: ekbharani ***@***.***>, Comment ***@***.***> Subject: Re: [chocolatey-community/chocolatey-coreteampackages] (googlechrome) SessionNotCreatedException: Message: session not created (#1722) 
Is this an issue with the package or with Google Chrome?

**Comment by elveera0491** [comment]
I second that. It seems to be an issue with chrome and while running it remotely.

**Comment by pauby** [comment]
@ekbharani Whose response are we waiting on? It's not clear from the thread.

**Comment by elveera0491** [comment]
It seems to be fixed with latest chromedriver v95.0.4638.540 and chrome v95.0.4638.69. Not sure what was the fix but I'm curious to know :)
