### ISSUE TITLE
(PDF Creator) 4.4 released 8/31 but not updated

### ISSUE THREAD

**Issue by user8446** [chocolatey-community/chocolatey-packages#1746]
Hello,

PDF Creator 4.4 was released 8/31 but as of now is still on v4.3. Since this is chocolately-community maintained, just raising an issue here since it may have been overlooked.
Thank you!

**Comment by ScoobyDone** [comment]
and now 4.4.1.....

**Comment by AdmiringWorm** [comment]
PDF Creator 4.4.1 have been pushed to Chocolatey Community Repository, it should be available for normal consumption once it passes all automated moderation checks in a few hours.

Fixed in commit: https://github.com/chocolatey-community/chocolatey-packages/commit/6009023dbf58fd94588df7044af713b5da60d6b1
