### ISSUE TITLE
Freecad package

### ISSUE THREAD

**Issue by niratouq** [chocolatey-community/chocolatey-packages#1762]
https://community.chocolatey.org/packages/freecad/0.19.2.7#files
There is  wrong x64 installer URL for Freecad package:
A "1" is missing at the end just before the dot.
The current URL is:
https://github.com/FreeCAD/FreeCAD/releases/download/0.19.2/FreeCAD-0.19.2.7b5e18a-WIN-x64-installer.exe
instead of:
https://github.com/FreeCAD/FreeCAD/releases/download/0.19.2/FreeCAD-0.19.2.7b5e18a-WIN-x64-installer1.exe

**Comment by RedBaron2** [comment]
@niratouq 
I appreciate your enthusiasm, but this issue is in the process of getting worked out (slowly). The powers that regulate this repository are looking into PR #1739
This will fix the URL error, and make it so minor changes like the 1/-1 won't halt the package (hopefully)
When the moderators are back from the holidays this PR should be merged, and the community will have working FreeCAD packages.

**Comment by pauby** [comment]
@niratouq Thanks for raising this issue. We do really appreciate interest from everybody in the community.

As there is a PR already open, I'll go ahead and close this as a duplicate, however we can always reopen it again in the future.

Thanks again.
