### ISSUE TITLE
HELP PLEASE - I've been using Chocolatey for a while, over a year, but now I can't log in

### ISSUE THREAD

**Issue by EngineerJack** [chocolatey-community/chocolatey-packages#1782]
About an hour ago, I was logged in, where I could click on packages, and settings, but it was taking forever to do its initial loading. While I was waiting, I went and turned on quite a few settings I hadn't previously had active, skimming the descriptions, yet I was activating premium, licensed options and I'm only a free user. I'm not cheap, but I don't have enough to spend on a license. Now when I try to log in, I get the error shown in the screenshot linked at the bottom, and it just crashes.

I'm not sure which version I have, but it's no older than a week or so, possibly two weeks.

I've been doing a lot of Googling and found [this](https://docs.chocolatey.org/en-us/choco/commands/config) tutorial, which describes how it is possible to access the options and switches in the configuration file when the program isn't running.

My first question would be, is there a simple command that allows us to turn off all of the premium options easily?

If not, what would be the easiest way to do so?

I have no problem turning every option off, then going back in and setting them afterward, but I really need to get it running, as I was working on something else, that requires it to update in Chocolatey before I am able to do anything else. So this has completely brought everything to a grinding halt.
<img width="763" alt="Chocolatey CTD Error" src="https://user-images.githubusercontent.com/93847350/148697757-1e3f1f87-f0b2-4272-b437-a35ffcee2717.png">

**Comment by TheCakeIsNaOH** [comment]
Hi, 

This repository is for packages uploaded by the `chocolatey-community` user on the Chocolatey community repository. Your issue appears to be with error in the the ChocolateyGUI program, not with a specific package on the community repository. 

Therefore, please open an issue at the ChocolateyGUI repository instead of here: https://github.com/chocolatey/ChocolateyGUI

> I went and turned on quite a few settings I hadn't previously had active, skimming the descriptions, yet I was activating premium, licensed options and I'm only a free user.

The options that are labeled as being only for the licensed editions are still available even if the licensed extension is not installed, but they should not doing anything if the licensed extension is not installed.

It appears most likely that there is a bug, where one of those licensed-only options actually did try to activate, but is failing because there is no license or licensed extension installed.

**Comment by iTouchU** [comment]
I just naturally found this forum first, so I assumed this was the correct one, and thanks for your help.

**Comment by gep13** [comment]
@TheCakeIsNaOH thank you. I will pick up that issue in the Chocolatey GUI repository.
