### ISSUE TITLE
(mumble) package is outdated

### ISSUE THREAD

**Issue by kuehnelth** [chocolatey-community/chocolatey-packages#1794]
Version 1.4.230 was released on January 17th. The version in Chocolatey is the previous one 1.3.4
Release page on github: https://github.com/mumble-voip/mumble/releases/tag/v1.4.230

**Comment by gep13** [comment]
Unfortunately, it looks like the version number formatting has changed in the latest release (it now includes a v at the start of the version number):

![image](https://user-images.githubusercontent.com/1271146/152494504-29ba3ef0-ddf1-4bce-b7d1-6bca70c912e6.png)

The regexes that are used within the update.ps1 file will need to be updated, as the version number that is found is `v1.4.230` rather than `1.4.230`.

**Comment by AdmiringWorm** [comment]
This has been fixed in the repository, and a new build is scheduled to be pushed to CCR.
