### ISSUE TITLE
(blender) Duplicate registry keys matched on uninstall

### ISSUE THREAD

**Issue by bedo2991** [chocolatey-community/chocolatey-packages#1795]
**choco uninstall blender**
```
Chocolatey v0.12.1
Uninstalling the following packages:
blender

blender v3.0.1
WARNING: 2 matches found!
WARNING: To prevent accidental data loss, no programs will be uninstalled.
WARNING: Please alert the package maintainer that the following keys were matched:
WARNING: - blender
WARNING: - blender
```

**Comment by pauby** [comment]
@bedo2991 Can you go back and complete the issue template in full?

As an FYI, I can't reproduce this after a straight install and uninstall:

```
PS C:\Users\WDAGUtilityAccount> choco uninstall blender
Chocolatey v0.12.1
Uninstalling the following packages:
blender

blender v3.0.1
Uninstalling blender...
0
blender has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - 'blender' appears to have been uninstalled already by other means.
 blender has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Users\WDAGUtilityAccount>
```

**Comment by TheCakeIsNaOH** [comment]
@pauby try installing blender `2.93.6`, then upgrading to the latest, then uninstalling.

**Comment by pauby** [comment]
@TheCakeIsNaOH okay, that breaks. 

The issue seems to be that blender doesn't uninstall the previous version on upgrade but simply installs the software again with the new version. After uninstalling the package / software, the previous version (2.93.6) is still there. Note that I haven't downloaded the installers to see if it's still an issue that way. I suspect it would be.

So, I'd say this is an installer issue and not a package one and is also expected behaviour by blender users. Having said that, we may want to look at only selecting a specific version to uninstall. Or if we agree it's not expected behaviour by blender users that we uninstall all versions. I'm not keen on that but it's an option.

**Comment by AdmiringWorm** [comment]
> So, I'd say this is an installer issue and not a package one and is also expected behaviour by blender users. Having said that, we may want to look at only selecting a specific version to uninstall. Or if we agree it's not expected behaviour by blender users that we uninstall all versions. I'm not keen on that but it's an option.

I believe that was something that is intentional, as there are quite common reasons why you would want to have several editions of blender installed (or at least it was when the versions 2.79 vs 2.80 was used).

So if we are going to remove the installer, we should specifically only remove the specific version. This causes some problems with upgrades though, as that would also need to know about removing the version we are upgrading from which we don't currently have any information about in the installation script.

**Comment by TheCakeIsNaOH** [comment]
> as that would also need to know about removing the version we are upgrading from which we don't currently have any information about in the installation script.

@gep13 mentioned wanting this information available in the Powershell environment, and I can see the value in it. I'm not finding an issue about it though.

**Comment by gep13** [comment]
@TheCakeIsNaOH I honestly can't remember if an issue has been created for this or not. It is something that has come up a number of times though, i.e. having the information that this is an upgrade or an install.  And if it is an uprade, what version is being upgraded from.

**Comment by AdmiringWorm** [comment]
Currently, the only issue I know of that exists is to provide the previous version during an upgrade (this is what I had in mind for the information we would need as well).
https://github.com/chocolatey/choco/issues/1713
