### ISSUE TITLE
(GeForce Experience) Install error 9

### ISSUE THREAD

**Issue by AndrewIsBest69** [chocolatey-community/chocolatey-packages#1813]
### Chocolatey Version

0.12.1

### Package Version

3.25.0.84

### Current Behaviour

When installing this package, I get the following error:
`geforce-experience (exited 9) - Error while running 'C:\ProgramData\chocolatey\lib\geforce-experience\tools\chocolateyInstall.ps1'.`

### Steps To Reproduce

1. Install GeForce Experience
2. See error 9

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 5.1.22000.282
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/AndrewIsBest69/a7acba1ee1a703f20660863779cfac9c
```

**Comment by AdmiringWorm** [comment]
I am not sure how you came to this repository for the package you are mentioning.

the GeForce Experience package is not maintained in this repository, or by us, as such you'll need to contact the maintainer of the package to get it fixed.

This can be done by navigating to the package on the community website and clicking on the `Contact Maintainers` link listed there.
If they have their own repository where they keep the package, this is also usually provided on the package page by the maintainer and will show up as a link on the left side of the page.

Because this package is not maintained by us, I will be closing this issue.
