### ISSUE TITLE
(nmap) Install is not silent

### ISSUE THREAD

**Issue by akusei** [chocolatey-community/chocolatey-packages#1823]
### Chocolatey Version

0.12.1

### Package Version

7.9.2

### Current Behaviour

Installing package nmap version 7.9.2 is not able to complete silently with the current autohotkey script

### Expected Behaviour

The nmap package is installed silently with no user input required

### Steps To Reproduce

1. run choco install nmap -y
2. npcap setup appears and chocolatey waits indefinitely for the npcap setup to complete

### Environment

```markdown
- Operating System: Windows 10
- .NET Framework: 4.8
- PowerShell Version: 5.1
- Shell: PowerShell terminal
```

### Chocolatey Log

```shell
https://pastebin.com/s9MdbUns
```

### Anything else?

This is a known issue, I don't know why the original one was closed and never fixed, especially when the main branch shows it as fixed but chocolatey is not using that version. 

Original issue I found: #1557 

[/automatic/nmap/tools/install.ahk](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/nmap/tools/install.ahk) has the fix and was merged around 7 months ago with this commit [60684a0](https://github.com/chocolatey-community/chocolatey-packages/commit/60684a02abee52af97e76c670fba30d89a6ab269) on [PR 471](https://github.com/chocolatey-community/chocolatey-packages/pull/471)

Why is chocolatey still downloading an old broken package 7 months after it has been fixed?

**Comment by pauby** [comment]
> Why is chocolatey still downloading an old broken package 7 months after it has been fixed?

I think the issue was that it either wasn't fully fixed. Or it was fixed and the installer has changed so it needs fixed again. Chocolatey isn't downloading an old broken package.

The problem appears to be with the `npcap` installer, NOT the `nmap` installer. They are run from the same Chocolatey package install. You can see below that the `nmap` part works fine. It stops at `npcap`

![nmap-installer](https://user-images.githubusercontent.com/12760779/158916479-e65a3ead-c2d2-42ce-8a8a-39837d99bca5.gif)

There is a separate [`npcap`](https://community.chocolatey.org/packages/npcap/) package that is no longer maintained due the the developers not supporting it. The `npcap` package would still require AHK.

**Comment by AdmiringWorm** [comment]
This is now fixed in the repository, and a new fix version of nmap have been scheduled to be pushed to CCR.
