### ISSUE TITLE
(vim) Path for batch files should not be into system Windows folder

### ISSUE THREAD

**Issue by gsmitheidw** [chocolatey-community/chocolatey-packages#1943]
### Chocolatey Version

1.1.0

### Package Version

9.0.0040

### Current Behaviour

I noticed an uninstall is removing "$env:windir\vimtutor.bat"
I would consider this a bad location for any scripts that come with vim because:

1. A user would not expect to find files spread across the system, where possible they should be kept together and tidy in one path. 
2. A feature upgrade of Windows would move the old installation to Windows.old so this file would be orphaned, lost or not executable

### Expected Behaviour

vim files found in one consolidated location (where possible) matching the install path as chosen on install. Nothing written to c:\windows\* or equivalent

### Steps To Reproduce

Install vim with chocolatey

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 5.1.22000.653
- Shell: Windows Terminal
```

### Chocolatey Log

```shell
n/a
```

**Comment by AdmiringWorm** [comment]
A agree that files should not be installed to the windows directory without a good reason, I am a bit hesitant to change this without further knowledge about why this was chosen and has been doing that since 2019, with this is the first time someone has mentioned it (at least here on GitHub).

@matsuhav, as the one that worked on this package, do you remember why it was decided to copy the `vimtutor.bat` file into the windows folder?

**Comment by matsuhav** [comment]
I agree with you @AdmiringWorm .
I think we should stop copying it.
Messing around system directories like `windir` is a bad idea and Chocolatey should not touch them.

Even more, I did some quick experiments on the latest version and found that
1. `vimtutor.bat` created by the installer differs from what we are currently copying.
2. The copied `vimtutor.bat` is not even working properly. It cannot run GVim(GUI version of Vim).

We should definitely stop copying it for those reasons.

And, as a better fix, maybe we can create `vimtutor.bat` in proper manner by `install.exe`, though it is not documented. (i.e. 5th background explained later was false?)
https://github.com/vim/vim/blob/master/src/dosinst.c#L2421
https://github.com/vim/vim/blob/master/src/dosinst.h#L359
https://github.com/vim/vim/blob/master/src/dosinst.c#L2377

---

As a background, IIRC,
1. `vim-win32-installer` offers two install options: Zip installation and installer.
2. I chose Zip installation over installer because the installer didn't offer some installation options which were supported by the old `vim` package which was based on Cream.
4. Zip installation should be done by unzipping it and running unzipped `install.exe`.
5. However, Zip installation and installer didn't do the same thing.
    - The installer had created `view.bat`, `vim.bat`, `vimdiff.bat` and `vimtutor.bat` in `windir`.
    - `install.exe` had created all above but `vimtutor.bat` in `windir`.
    (These bat files make `vim` commands available in cmd.exe and Powershell. So, Zip installation didn't offer `vimtutor` command)
6. When I copied `vimtutor.bat` to `windir`, `vimtutor` command worked.
7. I decided to copy it because I thought `vimtutor` command may be used by some introductory materials and should be available.

**Comment by matsuhav** [comment]
In summary, I think there are two issues around batch files:
1. batch files are generated in `windir`.
2. Copying `vimtutor.bat` part of install script is broken.

I made a commit which solves the latter here https://github.com/matsuhav/chocolatey-packages/commit/8b0935d842386a470d6f96c8dbec1b49d5a71c18

About the former, I inspected the behaviors and codes of installers.
Both `install.exe` in Zip installation and the installer generate batch files in `windir` by default and there are no options controlling the location.
But we can workaround this. Because `install.exe` searches for and overwrites batch files found in PATH, we can create dummy batch files in `$env:ChocolateyInstall\bin` beforehand and make it overwrite them.
I implemented this at https://github.com/matsuhav/chocolatey-packages/commit/94a292938e2fb3e367b562ad1ee4566f519f4d70

Changing the default location bothers me somehow, but these batch files are for interactive shell command and should not break anything.

**Comment by gsmitheidw** [comment]
@matsuhav as I was saying on [another vim installer issue](https://github.com/chocolatey-community/chocolatey-packages/discussions/1944#discussioncomment-3229824)  - this is upstream problems with vim's installer mechanism. Maybe the solution is to fix the source of the problems raising issues with vim itself here: https://github.com/vim/vim-win32-installer   rather than trying to figure a way to post-process the sprawl of files in the wrong places/wrong permissions.

**Comment by matsuhav** [comment]
Yes, there is no clean way for us to specify where batch files are installed as far as I can tell.

Maybe we should update the title of this issue to something like "Path for batch files should not be ..." because `vim` package installs 8 batch files in `windir` in total.
Bad handling of `vimtutor.bat` made us become aware of this issue but this is not limited to `vimtutor.bat`.

**Comment by matsuhav** [comment]
@pauby
I'm not working on this now since we identified this as an upstream issue.

If the workaround I wrote earlier (quoted below) looks good to you, I'll make a PR.
Because it's a little bit hacky and can break in the future, I want your thoughts on this.

> But we can workaround this. Because install.exe searches for and overwrites batch files found in PATH, we can create dummy batch files in $env:ChocolateyInstall\bin beforehand and make it overwrite them.
I implemented this at matsuhav@94a2929

**Comment by pauby** [comment]
The changes you're making create files directly in the Chocolatey `bin` directory, which for the Chocolatey Community Repository isn't allowed. 😭

**Comment by matsuhav** [comment]
Thank you for your comment. I was not aware of that. Well, I should have thought about that. It is an obvious rule to prevent dependency and conflict hell.

So, our only option is to implement these operations?
When installing,
1. Create some directory somewhere in vim package destination
2. Add it to PATH
3. Put empty dummy batch files in it
(and `install.exe` will overwrite them with real ones)

When uninstalling,
1. remove the directory from PATH

**Comment by AdmiringWorm** [comment]
> So, our only option is to implement these operations? When installing,
> 
> 1. Create some directory somewhere in vim package destination
> 2. Add it to PATH
> 3. Put empty dummy batch files in it
>    (and `install.exe` will overwrite them with real ones)

I would suggest a bit different approach.

1. Create a vim directory in `C:\tools` folder (a user can configure this folder, and can be grabbed through the [`Get-ToolsLocation`](https://docs.chocolatey.org/en-us/create/functions/get-toolslocation#notes) helper)
2. Add it to PATH
3. Can't speak of this one, but sure if the dummy file is needed then yeah.

On Uninstall
1. Remove the directory from PATH
2. Remove the directory itself
