### ISSUE TITLE
(ccleaner) Package not being automatically updated

### ISSUE THREAD

**Issue by steve78b** [chocolatey-community/chocolatey-packages#1960]
### Chocolatey Version

1.1.0

### Package Version

6.02

### Current Behaviour

The package is not being automatically updated. 

This is because piriform have changed the HTML on their versions page, to add a &lt;span&gt; after the &lt;h6&gt;.
so this line in the update.ps1 file
    $download_page.Content -match '\<h6\>v((?:[\d]\.)[\d\.]+)'
will never match.

I'm not good at regex, so I'm reluctant to propose a fix

### Expected Behaviour

Automatic updates

### Steps To Reproduce

I Can't run the automatic updater, as I don't know how to

### Environment

```markdown
- Operating System: windows 10
- PowerShell Version: 7.25
- Shell:
```

### Chocolatey Log

```shell
Not relevant as the bug is server side
```

**Comment by brogers5** [comment]
@steve78b, you'd only need the [AU module installed](https://community.chocolatey.org/packages/au) to reproduce locally. Running the `ccleaner` package's `update.ps1` script should then trigger a failed update.

I've confirmed `\<span data-qa-id="version-history__latest-version"\>v((?:[\d]\.)[\d\.]+)` would be a valid match for the version history page's current state.

However, CCleaner also supports checking for updates, so IMO we should consider querying the official endpoint going forward, instead of scraping the version history page.

Example implementation:

```powershell
$download_page = Invoke-WebRequest 'https://www.ccleaner.com/auto?p=cc' -UseBasicParsing
$version = $download_page.Content.Split('|')[2]
```

**Comment by RedBaron2** [comment]
@brogers5 
That is a very good catch and could work very well for the update script for this package. You wouldn't by chance like to open a PR with the necessary changes?

**Comment by brogers5** [comment]
@RedBaron2, sure, I'll pick this one up.
