### ISSUE TITLE
(codelite) Installing 15.0 vs 16.0

### ISSUE THREAD

**Issue by moklinowski** [chocolatey-community/chocolatey-packages#1965]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

16.0

### Download location

https://downloads.codelite.org/downloads.php?windows_64

### Package Page

https://community.chocolatey.org/packages/codelite

**Comment by brogers5** [comment]
The package is outdated because the update script is failing. `URL32` as defined in `global:au_GetLatest()` has stopped being populated. This is because Codelite has stopped publishing 32-bit installer binaries as of v15.0.4, so the package should drop support for 32-bit installations going forward.
