### ISSUE TITLE
(minikube) is outdated

### ISSUE THREAD

**Issue by jeffmaury** [chocolatey-community/chocolatey-packages#1994]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.30.0

### Download location

https://github.com/kubernetes/minikube/releases/download/v1.27.0/minikube-windows-amd64.exe

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/minikube

**Comment by brogers5** [comment]
This package is outdated because the update script is currently broken.

This is due to a wider issue that relates to a recently rolled out change with GitHub's Release pages. In the interest of DRY, I'll just link to my thoughts for a similarly affected package: https://github.com/chocolatey-community/chocolatey-packages/issues/1995#issuecomment-1275548394

In this case, it looks like we're only scraping a version number. We might be able to get away with scraping this from the tag's name.

Core maintainers: perhaps we ought to consider a larger meta issue if a common fix is preferable for all affected packages.

**Comment by pauby** [comment]
@brogers5 I've done that over at #2007 and added this package to that issue.
