### ISSUE TITLE
(git) outdated

### ISSUE THREAD

**Issue by vls-tomra** [chocolatey-community/chocolatey-packages#1995]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.38.0

### Download location

https://git-scm.com/download/win

### Package Page

https://community.chocolatey.org/packages/git

**Comment by vls-tomra** [comment]
when creating this ticket i found it very hard to navigate the "moderation queue". I ended up manually going through this queue, but it is not clear to me where I can "log in"...

**Comment by brogers5** [comment]
This package is outdated because it depends on version information sourced by `git.install`'s update script, which itself is currently broken.

`git.install`'s update script currently implements scraping the project's latest Release page on GitHub. GitHub recently rolled out a change to Release pages that involves lazy-loading the Asset links associated with a given Release. Unfortunately, the script also depended on the legacy behavior of these links being eager-loaded, and thus the relevant Asset links are not captured or found within the resulting response.

This package (among many others with release artifacts hosted by GitHub) will now need an alternate approach. I personally would lean toward querying GitHub's API if practical. Ideally, this would be done with API key authentication to help fend off possible rate-limiting (especially for a repository of this scale), although it could introduce some complications inherent to secret management. Alternatively, we could implement another anonymous-access based approach, such as scraping the provided Download Location page.

**Comment by StefanScherer** [comment]
Would be good to have the version 2.38.1 available via chocolatey. This version covers the latest [CVE-2022-39253](https://github.blog/2022-10-18-git-security-vulnerabilities-announced/). Thank you!

**Comment by pauby** [comment]
@StefanScherer See issue #2007 and PR #2013 - we're working on it!
