### ISSUE TITLE
(itunes) Upgrade false positive if software is running

### ISSUE THREAD

**Issue by awebeer256** [chocolatey-community/chocolatey-packages#2045]
### Chocolatey Version

Other (note in the comments)

### Chocolatey License

None (FOSS)

### Package Version

12.12.5.8 -> 12.12.6.1

### Current Behaviour

If you run `choco upgrade itunes` while iTunes is running, then the upgrade will fail, but Chocolatey will believe that it succeeded and requires a reboot.

### Expected Behaviour

If you run `choco upgrade itunes` while iTunes is running, then the upgrade should fail and Chocolatey should know that it failed.

### Steps To Reproduce

1. In an environment where the Chocolatey package `itunes` has been installed and is out of date…
2. Open iTunes.
3. Run `choco upgrade itunes`.
4. Run `choco outdated`. The output will not list `itunes`.
5. Reboot the computer.
6. Run `choco outdated` again. The output will still not list `itunes`.
7. Run `choco upgrade itunes`. The output will report that it is already up to date.
8. Open Programs and Features, and check the listed version number for iTunes. It will be the old version number.
9. Open iTunes, and go to Help -> About iTunes. It will report that it is the old version.

### Environment

```markdown
- Operating System: 10.0.19045.0
- PowerShell Version: 5.1.19041.1682
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/awebeer256/6b0db6cb62c366a4574256d1a2d2efb7
```

### Anything else?

Chocolatey version 1.2.0

**Comment by AdmiringWorm** [comment]
Thank you for opening the issue. Unfortunately, what you describe and what the shared log file says do not match.

You say that Chocolatey says the installation succeeded, and you expected it to fail. However, the shared log file says it failed to install the package. So the expected behavior that you detailed matches what is happening.

Now, there is a known bug in Chocolatey CLI itself at the moment that occurs at times when it will forget about a package if it fails to upgrade. This fits with the information you give about it not showing up when you run `choco outdated`. To see whether this is the case, run `choco list -lo` and see if iTunes is listed as an installed package.
In the end, given the behavior you detailed, the expected behavior, and the log file you link to, nothing could be done as part of the package to change the behavior.

One thing we could do as part of the package to prevent the need for a reboot is to explicitly kill/shut down the iTunes process before trying the installation.

**Comment by awebeer256** [comment]
I was too imprecise with my language. Yes, Chocolatey outputs a message saying it failed to install the package, but it still changes its belief about which version of the package is installed:
```
choco list -l -> iTunes 12.12.5.8
choco upgrade itunes
choco list -l -> iTunes 12.12.6.1
```
It now believes that the newer version is installed, when in fact the old version is still installed. This is what I meant when I said it believes that the upgrade succeeded.

Is this the known bug you're talking about?

**Comment by AdmiringWorm** [comment]
I couldn't find anything immediately, unfortunately. Can I ask you to open up an issue at https://github.com/chocolatey/choco/issues using its bug template (it differs from the one used here, as the circumstances are different)?

I will be closing the issue here, as it is not a problem in the package itself but rather a bug in Chocolatey CLI.
Feel free to reference this issue in the issue you create on the other repository though.

**Comment by awebeer256** [comment]
Okay, I'll do that. Thanks for your help.

**Comment by awebeer256** [comment]
…Or not. I was trying to recreate the problem to submit there, and this time, the upgrade force-closed iTunes and succeeded. 🤷
