### ISSUE TITLE
(git) Update to Version 2.39.0 (2) from 21th of december 2022  

### ISSUE THREAD

**Issue by serious6** [chocolatey-community/chocolatey-packages#2102]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

v2.39.0.windows.2

### Download location

https://github.com/git-for-windows/git/tree/v2.39.0.windows.2

### Package Page

https://community.chocolatey.org/packages/git

**Comment by serious6** [comment]
Sidenote: Current distribution from chocolatey package is with Version Git 2.39.0 but from Monday, December 12, 2022. So not reflecting [Git for Windows 2.39.0(2)](https://github.com/git-for-windows/git/releases/tag/v2.39.0.windows.2).

**Comment by serious6** [comment]
Manual workaround: perform `git update-git-for-windows` so the latest version will be used. Seems not to cause any trouble for chocolatey.

**Comment by TheCakeIsNaOH** [comment]
The package is still outdated, so reopening this issue.

**Comment by pauby** [comment]
The previous GitHub repository tag was `2.39.0.windows.1` and the latest tag is `2.39.0.windows.2`.

The [`update.ps1`](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/git.install/update.ps1#L39-L42) sees both of those as 2.39.0 as it only looks at the text before `.windows`. If we amend the detection logic to use any number after the `.windows` as part of the version number, then the last version would be 2.39.0.1 (which is incorrect).

This latest release is a feature and bug fix release so, using semver, I'd suggest it should have been a 2.40.0 release. I believe that a 2.39.0.2 release is a mistake.

I' don't think there is nothing we want to do here, and we should close this. Amending the logic isn't too difficult, but it's going to get things wrong in future. As suggested, the issue is with the versioning of the git software release and not with the detection logic here.

**Comment by serious6** [comment]
Not sure what you mean with "I believe that a 2.39.0.2 release is a mistake.". The mentioned release comes with new features as well as bug fixes which now remain unfixed for all chocolatey users except they do a manual update.

I personally would consider this unacceptable and your discission of adding "invalid / not implementing" on this actually worries me having security in mind with regards to future updates or other packages.

**Comment by pauby** [comment]
> Not sure what you mean with "I believe that a 2.39.0.2 release is a mistake.". The mentioned release comes with new features as well as bug fixes which now remain unfixed for all chocolatey users except they do a manual update.

You didn't quote the full sentence, which gives it context.

> This latest release is a feature and bug fix release so, using semver, I'd suggest it should have been a 2.40.0 release. I believe that a 2.39.0.2 release is a mistake.

A bug fix and feature release should be a 2.40.0 release, according to [semver](https://semver.org) (which they seem to be following). Had they released that, the tag would have been 2.40.windows.1 which would have been picked up automatically and a new version released. They released a 2.39.0.2 release which is a 'patch' release (minor minor fix) which they tagged 2.39.0.windows.2. The detection logic ignores `.windows` and anything after it. So, the detection logic picked this up as version 2.39.0, which is the same as the last released version, and it is why it didn't pick it up.

If we alter the detection logic to use the number after windows, then the tag _for the last version_ would have been `2.39.0.windows.1` which would have resulted in a version of 2.39.0.1 which is incorrect. So, we either use the number after `.windows`, we don't, or we come up with some complex logic that _we_ have to maintain. 

> I personally would consider this unacceptable and your discission of adding "invalid / not implementing" on this actually worries me having security in mind with regards to future updates or other packages.

Just to be clear, this is _not_ a security update and there are no security issues fixed in this release by Git or any of the bundled software updates. Using their version numbering, this is a patch release - which is why I suggest we don't fix it. The last time there was a git security release, it was pushed out very quickly.

This repository is managed by the Chocolatey Community, not Chocolatey. It's a community maintained effort, and any member of the community can submit a PR to fix issues that they find. Any changes need to be handled by the community and maintained. If things get too complex, then there will be fewer people willing to pick them up. _My_ suggestion is that we don't fix this, but anybody is free to disagree and submit a PR to fix it. If that happens, I'll change the labels.

I'm waiting to hear other opinions, which is why I didn't close the issue but simply changed the labels.

**Comment by pauby** [comment]
Looking at the Git For Windows page, the version number is displayed there.

![image (8)](https://user-images.githubusercontent.com/12760779/212923203-f8c512ef-cce9-4b08-9762-8df3c8ef8923.png)

And the assets have a version number in there.

![image (9)](https://user-images.githubusercontent.com/12760779/212923266-3b6c8868-f00e-4740-a468-41c26e5d2a3e.png)

After speaking to a colleague, it now makes sense the version number they are using. Git is at 2.39.0 and Git For Windows at 2.39.0.2. If they released a 2.40.0 version of Git For Windows, then they would be out of step with everything else.

![image](https://user-images.githubusercontent.com/12760779/212923697-cd98befc-4695-4733-aaed-498e72be7896.png)

The version detection logic uses tags which seem problematic. Perhaps we can grab the version from the Git For Windows page or by parsing the latest assets released. This may have been done in the past, and then a switch to tagging was made. I'm not aware of the history. Somebody else would be better placed to comment on that.

**Comment by pauby** [comment]
I spoke to @AdmiringWorm earlier on this.

The patch / revision releases (in this case 2.39.0.2) are not normally updated and pushed as they generally contain minor updates. All other versions are pushed normally.

I have added a [featured comment to the package page](https://community.chocolatey.org/packages/git.install#discussion) that clarifies this.

![image](https://user-images.githubusercontent.com/12760779/213174907-cb269f49-b055-4d6e-be39-cfe7bda63f31.png)

As there is nothing more to do here and [version 2.39.1 has now been pushed and approved](https://community.chocolatey.org/packages/git.install/2.39.1), I'll go ahead and close this issue.
