### ISSUE TITLE
(blender) `choco upgrade` does not uninstall current version before installing the new version

### ISSUE THREAD

**Issue by jedfrechette** [chocolatey-community/chocolatey-packages#2156]
### Chocolatey Version

1.3.0

### Chocolatey License

None

### Package Version

all recent

### Current Behaviour

The command:

`choco upgrade blender`

does not uninstall the currently installed version and simply installs the most current version. This directly leads to issues such as #1795 and makes `choco upgrade all` useless on any machine that has Blender installed unless the user is OK with either ending up with dozens of Blender versions installed and unmanged by Chocolately or can manage Blender upgrades separately from their other packages.

### Expected Behaviour

Coming from other package management systems I would expect `upgrade` to uninstall the currently installed version of a package and install the latest version. This is also how most other Chocolatey packages seem to behave.

In the discussion on #1795 @AdmiringWorm mentions that the Blender package's current behavior may have been an intentional decision as users may want to have multiple versions installed. I was not able to find any other discussion regarding that decision, however, while I agree that there are valid use cases for having multiple versions of Blender installed I would argue that the way the functionality is currently implemented by this package is not very user friendly as it relies on sideffects rather than explicit control by the user.

I've already described the problem with upgrades and Chocolatey losing control of installed Blender versions, which I think is the biggest problem with the current design as it affects all users. However, I think the current design is also not very good for the users who do want multiple versions installed. In the scenario where you want multiple versions you almost always want specific versions, not whatever the current versions happened to be when you ran `choco upgrade`. Therefore, I'd argue users who want multiple versions would be better off manually installing the ones they want by using `-m` (AllowMultiple versions) as illustrated in the documentation's ruby example: 

https://docs.chocolatey.org/en-us/choco/commands/install#examples

If, however, the Blender package does really need to handle automatic side by side installations it seems like the right way to do that would be with versioned package names plus a metapackage as described in the developer docs:

https://docs.chocolatey.org/en-us/create/create-packages#if-the-software-youre-creating-a-package-for-expects-side-by-side-installations-of-different-versions

However, given how frequent Blender releases are and how much extra effort that would require it seems unnecessary for this situation. I think the best solution would be to fix the Blender package to uninstall the currently installed version on upgrade, like other packages do, and allow users how need multiple versions to manage them using Chocolatey's built-in functionality for doing just that.

### Steps To Reproduce

1. `choco install blender`
2. Wait until a new Blender release
3. `choco upgrade all`
4. Repeat steps 2 and 3 a few times.
5. Go to Programs and Features and count how many copies of Blender you have installed.

### Environment

```markdown
NA
```

### Chocolatey Log

```shell
NA
```

**Comment by TheCakeIsNaOH** [comment]
> Therefore, I'd argue users who want multiple versions would be better off manually installing the ones they want by using -m (AllowMultiple versions) as illustrated in the documentation's ruby example:

The `-m` switch is deprecated and will be removed in the next major version of Chocolatey CLI, so it is not something that should be relied upon for this.

> I think the best solution would be to fix the Blender package to uninstall the currently installed version on upgrade, like other packages do

Most other packages do not explicitly uninstall older software versions during upgrade. Instead, the software installer will remove/upgrade older version(s) while the installer is running.

**Comment by jedfrechette** [comment]
> Most other packages do not explicitly uninstall older software versions during upgrade. Instead, the software installer will remove/upgrade older version(s) while the installer is running.

We might be saying the same thing, but just to be clear if I have versions 1, 2, and 3 of a piece of software installed and the package for version 4 gets released I wouldn't necessarily expect `choco upgrade foo` to do anything with versions 1 and 2 but I would expect it to uninstall 3 and install 4. That's how most other Chocolatey packages I've used behave.

Other package managers like apt wouldn't even allow you to get in to that scenario as having multiple versions of the same package installed at the same time isn't permitted so deprecating the `-m` switch is probably the right move for Chocolatey and, I'd argue, is another argument against the Blender package's current behavior.

A concrete example of a package that I think behaves correctly is `pycharm-community`. If I have version 2022.3.1 installed it is installed to the versioned directory `C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1`. If I run `choco upgrade pycharm-community` version 2022.3.1 get's uninstalled and the versioned directory is deleted then the current version (2022.3.2 as of this writing) get's installed.

**Comment by pauby** [comment]
Just to be clear Chocolatey manages packages. Packages manage software. Chocolatey doesn't manage software.

If Blender allows you to installed l have multiple versions of their software installed and doesn't uninstall them before upgrading to the new one, then that is expected behaviour for Blender from Blender users. Chocolatey packages should follow that in my opinion.

This is the same behaviour for major versions of Camtasia and SnagIt (that I maintain). Again it's expected behaviour. I appreciate you day that is not how other packages you use, behave, but there are many installers that work this way.

If that behaviour should change then it should be the vendor / author that amends their installer. What the package could do is help with a parameter that says uninstall all previous versions first, but that should not be the default behaviour.

You mentioned about other package managers doing this. Linux for example does not have to deal with the landscape that Chocolatey CLI has to, on Windows. On Linux your package manager is required to install software so it's a known (almost sealed) bubble in that the package manager can make educated decisions on what to do.

Windows is not like that. On Windows the user has traditionally downloaded software manually. So the known bubble that is there on Linux is simply not there on Windows. The decisions that have to be made by Chocolatey CLI must err on the side of caution to avoid having the user end up in a situation that they did not intend.

Coming back to this package though a package parameter would be nice to add and I think an issue would be good for that. Otherwise, I don't feel there isn't anything for us to do here because it is expected behaviour.

**Comment by jedfrechette** [comment]
> If Blender allows you to installed l have multiple versions of their software installed and doesn't uninstall them before upgrading to the new one, then that is expected behaviour for Blender from Blender users. Chocolatey packages should follow that in my opinion.
> 
> This is the same behaviour for major versions of Camtasia and SnagIt (that I maintain).

For packages like this where the installers don't do in-place upgrades would it make sense for `choco upgrade` to be a null op or report an error?

If we think of the choco package as just a thin wrapper around the upstream installer always doing `choco install` or `choco uninstall` would be a much more accurate representation of their capabilities. I think choco losing control of previous versions of the software that it has installed is still a problem, but at least the actions it supports would be more explicit with this type of approach.

>Again it's expected behaviour. I appreciate you day that is not how other packages you use, behave, but there are many installers that work this way.

I guess what's expected depends on how you're approaching this. As a user, one of my main reasons for using choco is to abstract interaction with installers, therefore, my expectation is that all packages will behave as similarly as possible. I use it, in part, so that I don't have to know how each individual installer behaves. While I understand the difficulties involved, I think that is a reasonable expectation given that the choco developers directly compare it to linux package managers.

Looking at this a different way. What if this package shipped the portable version of Blender?  Clearly the upstream zip file doesn't have any built-in functionality for upgrades or uninstallation, does that mean the choco package shouldn't handle those aspects either? I don't think anyone would argue that such a package should

**Comment by jedfrechette** [comment]
Sorry, accidentally closed.

**Comment by jedfrechette** [comment]
Sorry, closed accidentally

**Comment by pauby** [comment]
> For packages like this where the installers don't do in-place upgrades would it make sense for choco upgrade to be a null op or report an error?

Remember Chocolatey doesn't manage software. It's the packages responsibility to do that. I know we're in the packages repository, but I'm just highlighting that.

> I guess what's expected depends on how you're approaching this. 

Expected behaviour would be "what does the installer do" and therefore what would the average user of the _software_ expect.

> While I understand the difficulties involved, I think that is a reasonable expectation given that the choco developers directly compare it to linux package managers.

I don't disagree. But we need to remember that the Windows ecosystem is a lot more complicated and varied than Linux and we have to err on the side of caution and take into account that Chocolatey may not be the first thing people install, nor that people _only_ use it to install software. And therefore their system is going to be a a complicated, messy environment to work on and make decisions about.

We use the familiarity of Linux and Mac package managers as a way for people to understand what Chocolatey is in the quickest time possible without having to explain what a package manager is which isn't an easy concept to grasp. As I said, most Windows users download and install software manually and are likely to be less technical than Linux and Mac users (that's based on my experience and nothing more). So we are unable to mimic what Linux and Mac package managers do completely and we don't pretend that we do 

Some features or functions are considered to equivalent Linux or Mac package managers functions too. And we like to function in the same way when possible. But all of that had to be balanced with that messy Windows ecosystem.

Your other statements are valid, and a package parameter, like I mentioned previously, would solve this. If you want to implement that functionality I think it would be well received via a PR. But changing the default behaviour of the package, I would suggest, is a bad idea and not something I would be happy with. However, I'm only one voice in here.

**Comment by jedfrechette** [comment]
What kind of package parameter are you suggesting?

I guess the rest of it comes down to a more general question of whether a choco package should be a thin wrapper around an upstream installer or a uniform interface for installing, upgrading, and uninstalling software. Although I'm firmly in the later camp, I can see both arguments.

As for what's possible within the messy Windows ecosystem, here again, I'll point to `pycharm-community`. That software is exactly like Blender in that running the exe installer when a previous version is already installed will leave the current version alone and do an additional install of the new version rather than an in place upgrade. However, the maintainer of that package has chosen to make `choco upgrade` perform an in place upgrade [via chocolateyBeforeModify.ps1](https://github.com/mkevenaar/chocolatey-packages/blob/master/automatic/pycharm-community/tools/chocolateyBeforeModify.ps1) by uninstalling the currently installed version prior to installing the new version. That maintainer has almost as many packages in his repo as are in this one and uses the same pattern in several others so clearly reasonable people can come to different conclusions about what the right approach is.

I think these types of inconsistencies between packages maintained by different people is bad for users as they eliminate a lot of the benefits of something like Chocolatey so it would be great if the key maintainers could come to some kind of consensus about what the best approach should be. Is there any kind of community maintainers mailing list where these types of issues and best practices can get discussed?

**Comment by pauby** [comment]
> What kind of package parameter are you suggesting?

I mentioned it a couple of comments ago.

> As for what's possible within the messy Windows ecosystem, here again, I'll point to pycharm-community.

I understand what the maintainers of that package are doing and that is great and the user's of the pecans are expecting that behaviour.

With this package the users are expecting different behaviour. If the package does a thing and users redirect it to do that we cannot come along and change that. It's a bad idea experience.

Perhaps if the package did that from the beginning then perhaps that would make more sense, however I'd still argue it's unexpected behaviour for a user of the software but could be more sympathetic of the other argument.

> I think these types of inconsistencies between packages maintained by different people is bad for users

I agree and disagree. It depends what you mean by inconsistencies.

The users of this software expect it to keep around previous versions. That's what is always (I assume) done. So continuing with that behaviour is consistent.

If you mean some packages do it one way and others do it another then it is inconsistent. While I'd love to be consistency on all of that it's not feasible to enforce by the moderators and we rely on the maintainers to do the best job they can with the package and then somebody like you to come along and make suggestions to make it better.

Both of these are not wrong. It comes down to individual software expected behaviour and one size doesn't always fit all.

> Is there any kind of community maintainers mailing list where these types of issues and best practices can get discussed?

There isn't anything setup specifically for this. Not because we don't want to discuss it but because nobody has ever had anything other than the odd question.

Discord would probably be the best place under the [#community-maintainers channel](https://ch0.co/community).

I think for this we should come back to the issue at hand and the uninstalling previous versions of the software.

**Comment by pauby** [comment]
Have you raised this issue with the Blender author to fix their installer? Or get a confirmation that it's deliberate and an explanation as to why?

**Comment by jedfrechette** [comment]
> Have you raised this issue with the Blender author to fix their installer?

As a Blender user I consider their installer's current behavior to be correct. As discussed early there are important use cases for installing multiple specific versions at the same time. Their documentation for updating with the Windows installer also clearly notes that previous versions can be uninstalled via Windows Settings.

As a choco user I consider the current behavior to be a bug because `choco upgrade foo` does something different than `choco upgrade bar`

**Comment by pauby** [comment]
We are going to have to agree to disagree. Anything else I say will be repeating myself.

As I said above, this isn't a bug. This is expected behaviour by the package. I think having the best of both worlds would be to add a package parameter. If you want to submit a PR for that, then I don't see why it wouldn't be accepted. But, as I said before, I'm only one voice in here. I'll bow out of this now and let others jump in if they feel they want to.

**Comment by jedfrechette** [comment]
I think I've made my case as well I can too, but before moving on one last question:

> What the package could do is help with a parameter that says uninstall all previous versions first, but that should not be the default behaviour.

Based on this, would I be correct to assume you are also opposed to the Blender package adopting [the approach used by QGIS](https://community.chocolatey.org/packages/qgis#description)?

During upgrades the QGIS package attempts to remove the most recent previous version unless the user passes a parameter to keep the old version?

**Comment by pauby** [comment]
Doing that by _default_ would be changing the expected behaviour of an 11-year-old package. I would be opposed to it, but to be clear, and I know I'm repeating myself, I am only one voice in here. 

Adding a package parameter that would uninstall all previous versions seems to be the right balance and gives everybody what they want.

**Comment by pauby** [comment]
I have added the 'Up for grabs' issue. @jedfrechette can you add the functionality described above, via a PR?

**Comment by jedfrechette** [comment]
Adding a "Remove previous" parameter offers few benefits for my use case. For our work machines we've found it simpler and more reliable to just change the behavior of packages during internalization when we encounter ones like this that are inconsistent with the rest of our software stack.

At the moment, it would be difficult for me to justify spending time on a PR for a feature that I wouldn't use and wouldn't be able to test regularly. I'm not even sure exactly how I would want the proposed parameter to behave in the context of one or more previously installed versions that the user may or may not want to keep. If another user does have a use case for a "remove previous" parameter maybe they can outline how they would like it to behave in various scenarios or, even better, point to an existing package that has already implemented this functionality so that it could be used as a model.

Inconsistent behaviors and parameters on packages in the community repo is one of the big reasons we've found it easier to just normalize everything during internalization rather than try and keep track of all the variations at install time. I don't want to introduce even more variability for others by inventing something if some else has already implemented a solution that people are happy with.
