### ISSUE TITLE
(tortoisegit) Package upgrade fails if software was previously upgraded outside of Chocolatey

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-packages#2159]
### Chocolatey Version

1.3.0

### Chocolatey License

None

### Package Version

2.13.0.1 -> 2.14.0.0

### Current Behaviour

Installation fails with error code 1603, likely because the installer does not support a silent reinstallation.

### Expected Behaviour

Package should detect the currently installed version (if any) of TortoiseGit.

If the install/upgrade is not forced, and the packaged version matches the currently installed version, skip installation to avoid an installation failure.

### Steps To Reproduce

1. Install a previous version of TortoiseGit via Chocolatey (e.g. `choco install tortoisegit --version=2.13.0.1`).
2. Install a later version of TortoiseGit manually.
32-bit: https://download.tortoisegit.org/tgit/2.14.0.0/TortoiseGit-2.14.0.0-32bit.msi
64-bit: https://download.tortoisegit.org/tgit/2.14.0.0/TortoiseGit-2.14.0.0-64bit.msi
3. Upgrade to the corresponding Chocolatey package version (e.g. `choco upgrade tortoisegit --version=2.14.0.0`).

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19042.0
- PowerShell Version: 5.1.19041.2364
- Shell: Windows PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/brogers5/896f57853fc0c28652a4a985cafe7d1b
```

### Anything else?

Core maintainers: feel free to assign this to me.

**Comment by Jericho** [comment]
I am experiencing the same problem. Exactly as @brogers5 described, I installed tortoisegit using chocolatey and at some point I upgraded it manually because the choco package was not yet updated to the latest version. I didn't think this would be a problem. I thought, surely choco will realize I have a more recent version installed and won't bother telling me that I need to upgrade. 

To illustrate further, here what I see when I execute `choco outdated`:
![image](https://user-images.githubusercontent.com/112710/222907449-041b2004-c91b-4b9e-8075-b5ca93488ff6.png)

and here's the result when I execute `choco upgrade tortoisegit -y`:
![image](https://user-images.githubusercontent.com/112710/222907741-d223d509-d1cb-47ca-b6f9-85ab96dc615b.png)

To be crystal clear: I rebooted my machine to make sure to eliminate the possibility of a pending reboot causing this issue. I also tried append `-force` to the `choco upgrade` command and it failed with the same error message.

As an aside: does anybody know if there is a way to turn off tortoisegit's auto-update?

**Comment by pauby** [comment]
Thanks for raising this issue.

The Chocolatey Community Chocolatey Packages repository is maintained by community members. To resolve this issue, there are two options:

1. Wait for a current community maintainer to resolve the issue.
2. Look to resolve the issue yourself, submit a pull request and engage with the community.

We have documentation that will help you:

* [Code Of Conduct](https://github.com/chocolatey-community/chocolatey-packages#etiquette-regarding-communication)
* Repository [README](https://github.com/chocolatey-community/chocolatey-packages/blob/master/README.md).
* [How to contribute to this community repository](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md).
* [Status of packages in this repository](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f).

If you have any further questions, please add a [discussion](https://github.com/chocolatey-community/chocolatey-packages/discussions/categories/q-a).

**Comment by brogers5** [comment]
@Jericho, PR #2161 should resolve the issue.

In the meanwhile, you can upgrade the package with the `--skip-powershell` switch to skip running `chocolateyInstall.ps1`. As for TortoiseGit's auto-update option, the Settings dialog should expose this option on the General page.
![TortoiseGit AutoUpdate](https://user-images.githubusercontent.com/6869577/222919241-f74b6715-efd2-4c19-9873-d9458df5d814.png)

**Comment by Jericho** [comment]
@brogers5 thanks for the tip about `skip-powershell`. I wasn't aware of this switch. I tried it and it worked! I also turned off auto-update to avoid this problem until your PR is merged.
