### ISSUE TITLE
(ghostscript)(ghostscript.app)

### ISSUE THREAD

**Issue by nykBM** [chocolatey-community/chocolatey-packages#2173]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

10.0.0

### Download location

https://github.com/ArtifexSoftware/ghostpdl-downloads/releases

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/ghostscript.app and https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/ghostscript

**Comment by nykBM** [comment]
Both packages still show 9.56.1 on the community page.
https://community.chocolatey.org/packages/Ghostscript.app
https://community.chocolatey.org/packages/Ghostscript
With no update in the version history to 10.0.0

**Comment by brogers5** [comment]
Version 10.0.0 was automatically packaged and submitted, but failed validation due to an invalid `docsUrl`:
https://community.chocolatey.org/packages/ghostscript/10.0.0
https://community.chocolatey.org/packages/ghostscript.app/10.0.0

This was fixed by #2128, but revised packages with the change were never submitted, so they never made it past moderation.

Looks like either we're waiting out a new version, or the admin team will need to move these back to the Submitted state, then a core maintainer will need to make AU rebuild and submit revised packages.

**Comment by pauby** [comment]
I force pushed AU, but it's submitted 10.0.0.20230317 versions rather than 10.0.0 🤦

**Comment by pauby** [comment]
These have now been approved. Version 10.0.0 of both packages has been rejected.
