### ISSUE TITLE
(Paint.Net) Unattended installation fails when running as SYSTEM

### ISSUE THREAD

**Issue by jmeile** [chocolatey-community/chocolatey-packages#2203]
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

5.0.2

### Current Behaviour

If you run:
`choco.exe upgrade all --yes`

as a scheduled task, Paint.Net won't be updated because its update process is not headless. It must show a GUI, but since the scheduler is not requiring it, it will fail.

### Expected Behaviour

Paint.Net should be updated

### Steps To Reproduce

1. Add a scheduled task that calls
   - Program/script: %ProgramData%\chocolatey\bin\choco.exe
   - arguments: upgrade all --yes --log-file="%ProgramData%\chocolatey\logs\upgrade.log"

3. install an old version of Paint.Net, e.g.:
    `choco install paint.net --version=5.0.1`

2. Then either logoff or manually run the task. Paint.Net won't be updated

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19042.0
- PowerShell Version: 5.1.19041.2673
```

### Chocolatey Log

```shell
2023-03-29 16:32:21,114 27712 [WARN ] - 
Chocolatey upgraded 0/10 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2023-03-29 16:32:21,117 27712 [INFO ] - 
2023-03-29 16:32:21,118 27712 [ERROR] - Failures
2023-03-29 16:32:21,120 27712 [ERROR] -  - paint.net (exited -532462766) - Error while running 'C:\ProgramData\chocolatey\lib\paint.net\tools\ChocolateyInstall.ps1'.
```

### Anything else?

I'm reopening this issue as suggested here:
https://github.com/chocolatey-community/chocolatey-packages/issues/1542

A possible solution would be to install the package as said here:
- Paint.net Silent Install (MSI) on 64-bit Systems
   https://silentinstallhq.com/paint-net-silent-install-how-to-guide

Here the instructions:
1. Navigate to: https://github.com/paintdotnet/release/releases
2. Download the paint.net.x.y.z.winmsi.x64.zip to a folder created at (C:\Downloads)
3. Extract the paint.net.x.y.z.winmsi.x64.msi from the paint.net.x.y.z.winmsi.x64.zip file to “C:\Downloads” using 7-Zip
4. Use the command: MsiExec.exe /i paint.net.x.y.z.winmsi.x64.msi /qn

If you don't want to fix this behavior, at least mention it on the package's page

**Comment by jmeile** [comment]
@pauby Sorry, but I don't understand what you mean with PR. What is this? A patch?

**Comment by jmeile** [comment]
Or are you meaning a package release maybe?

**Comment by pauby** [comment]
A PR is a pull request. This is a community repository so anybody can contribute.

In my [last comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1542#issuecomment-1487342319), I suggested you could raise so that _you_ could fix what you mentioned in [your comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1542#issuecomment-1487247085). If this issue is raised to ask _somebody else_ to fix it, my suggestion would be we close this issue as that's not what I meant and the issue didn't get any traction last time.

If you don't know how to contribute to this repository, that is entirely different and I'd suggest you have a look at how to raise a pull request in the first instance (lots of information on Google to help you with that).

**Comment by jmeile** [comment]
I will try this; however, I still think that those kind of problems: not headless installations failing updates, should be mentioned on the package information page.

**Comment by jmeile** [comment]
Yes, if you use the MSI installer, then you can solve the problem as follows:
https://silentinstallhq.com/paint-net-silent-install-how-to-guide

That's what I wanted to do, but since it is already in your TODO list, I will wait

**Comment by MrkGameDev** [comment]
Same problem over here, I opened an Issue about it before (#2116), And I didn't know why it behaves like this, Mainly because it sometimes... installs successfully?
It was confusing for me, and I did some research about MSI Silent Installations, but to no avail...

---------
Today, I did some trial-and-error, I found out that It does install Paint.net... but under the "general" tab, in your `choco Update Task`,  you'll have `Security Options` set like the following image:

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/70659536/b9150ed1-427c-4271-8e2a-96dea177633a)

 Of course... this takes the convenience away of not showing the Terminal Window when the task is running, _plus other GUI(s) that might pop-up when upgrading packages, like Paint.net window(s)_,
 So every time this task runs... you'll see choco running in a Terminal (CMD)... which isn't very annoying... but setting `Run whether user is logged in or not` did hide this window, Plus any GUI Window(s) like Paint.net Install Window(s).
 
---------
At the end, I still don't know why MSI Installation for Paint.net Insists on having The install window being showed, when the we passed Unattended Install Flag(s) to it.
