### ISSUE TITLE
Python 3.9.13  (CVE-2022-37454)

### ISSUE THREAD

**Issue by tortoise74** [chocolatey-community/chocolatey-packages#2232]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [ ] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.9.16

### Download location

https://www.python.org/downloads/release/python-3916/

### Package Page

https://community.chocolatey.org/packages/python39

**Comment by tortoise74** [comment]
There is a CVE with python 3.9 and a new version that addresses it - https://www.python.org/downloads/release/python-3916/

A complication with this version is that it is in a security patches only phase so no windows installer .exe is available. So it must be built from source.

See https://www.reddit.com/r/chocolatey/comments/13sb2lb/what_is_the_lead_time_for_cve_fixes_making_it/

**Comment by TheCakeIsNaOH** [comment]
> A complication with this version is that it is in a security patches only phase so no windows installer .exe is available. So it must be built from source.

As noted in the checklist above, an official binary must be available for an updated package to be added to the Chocolatey Community Repository. 

This is because all packages on the Community Repository must use only binaries from the official download location(s) for the software, and this behavior must be able to be verified. This can be accomplished in non-embedded packages by using the official download url for `Install-ChocolateyPackage` (or another helper, as appropriate). For embedded packages, this is accomplished by the `VERIFICATION.txt` file, which has steps that allow maintainers and users to verify that the included binary/binaries are the same as those available at the official download location.

Building the software from source during package installation is not something that is generally supported, and if it ever were to be supported, it would be a long way out: https://github.com/chocolatey/choco/issues/1709

If another party where to start building python 3.9 with the security fix, then that could be added to the Community Repository, but it would have to be under a new package ID. This is because people installing the `python39` (or version 3.9.x of `python`/`python3`) would be expecting an installer built by the python foundation, not by this hypothetical third party.

So unless I am missing something, unfortunately, the package cannot be updated to the lack of an official installer.

**Comment by tortoise74** [comment]
That suggests the correct thing to do might be to remove the package altogether and likewise any other and future versions of python that are in the "security only" part of the lifecycle.

Alternatively put some kind of warning about the package being out of date with respect to security patches. 

Note that theparticular CVE seems awkward to exploit (apparently you need to input 4Gb of data - but if you do you can hypthetically gain control).

Re a third party building the package. Do you need a long term commitment to maintenance or is it enough for random people to submit a build to the moderation queue occasionally for cases like this? (I can't see anything relevant on https://docs.chocolatey.org/en-us/create/create-packages)

**Comment by TheCakeIsNaOH** [comment]
> Re a third party building the package. Do you need a long term commitment to maintenance or is it enough for random people to submit a build to the moderation queue occasionally for cases like this?

Software != Chocolatey package.

The software is the program that is packaged up into a Chocolatey package. So the software is the Python 3.9.x `.exe` installer, the package is the `.nuspec`, `chocolateyInstall.ps1`, etc that is packaged up into a `.nupkg` file. 

If an official `.exe` was built, then it would be no issue for that to be packaged up into a new package version here. 

The problem is building the software installer, not the package.

**Comment by tortoise74** [comment]
That was my point. If I or any other random person (not the python foundation) was able to create the .exe installer would you accept that as a package? and if so would you require a commitment to also make 3.9.17 etc. when future issues come along?

**Comment by pauby** [comment]
> That was my point. If I or any other random person (not the python foundation) was able to create the .exe installer would you accept that as a package?

@TheCakeIsNaOH covered this in comments above. The answer would be no, it could not be accepted.

**Comment by pauby** [comment]
>  yes, they have a CVE associated with the old versions,

As mentioned on [Reddit](https://www.reddit.com/r/chocolatey/comments/13sb2lb/comment/jlq9t9e/?utm_source=reddit&utm_medium=web2x&context=3):

[CVE-2022-37454](https://nvd.nist.gov/vuln/detail/CVE-2022-37454) is for the Keccak XKCP SHA-3 implementation that Python uses. I also believe [PHP is affected](https://bugzilla.suse.com/show_bug.cgi?id=1204577#c19) at least on SUSE.
