### ISSUE TITLE
(curl) Doesn't install using PowerShell Core as the host

### ISSUE THREAD

**Issue by PietJankbal** [chocolatey-community/chocolatey-packages#2337]
### Chocolatey Version

1.4.0

### Chocolatey License

None

### Package Version

8.4.0

### Current Behaviour
I first run:

Hi, I would like to request a change of the install script.

Pre-note:  I always run like this first:     choco.exe feature disable --name=powershellHost
So I run with builtin powershell host disabled.

 Since a while it cannot be run anymore with success in PowerShell Core because of this line (it used to work before if I remember correctly):

Move-Item -Path "$toolsPath\cacert.pem" -Destination "$toolsPath\curl*\bin\curl-ca-bundle.crt" -Force

This gives: Error: Move-Item: Invalid name

Somehow this script got updated and now is broken for Powershell Core.

I asked somewhere else and if it could be changed to line below, it is compatitable with Powershell Core again. Thanks in advanc for updating the script..

Move-Item -Path "$toolsPath\cacert.pem" -Destination (Get-Item "$toolsPath\curl*\bin\curl-ca-bundle.crt") -Force

### Expected Behaviour

The script (also) succeeds in  Powershell Core

### Steps To Reproduce

run the script in Powershell core

### Environment

```markdown
- Operating System:
- PowerShell Version:Powershell Core 7.3.5
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/PietJankbal/d0a447ebf68f5e0f4df1cb35a8472c3f
```

**Comment by PietJankbal** [comment]
Hi, I forgot to mention that I disabled the builtin powershell host. So first I ran:

choco.exe feature disable --name=powershellHost

**Comment by pauby** [comment]
@PietJankbal The scenario that you are using (using PowerShell Core host with Chocolatey CLI scripts) isn't one that is common (I've never heard of it before). So this isn't an issue that the vast majority of people will run into.

Chocolatey CLI uses a Windows PowerShell host to run Chocolatey CLI scripts. Chocolatey CLI doesn't support PowerShell Core because it doesn't have to. Every Windows computer comes with Windows PowerShell.

Just to be clear on this repository. It is a community maintained repository, so when things need fixing / updating / changing, the expectation is that you submit those changes as a PR in the first instance.

Because the vast majority of people are never going to see this issue, I am guessing the community maintainers of this repository are unlikely to want to spend time fixing it. 

Hopefully, that gives some context as to why the above comments were made.

**Comment by PietJankbal** [comment]
closing as wontfix
