### ISSUE TITLE
(putty.install & putty) AU is not updating package scripts in the repository

### ISSUE THREAD

**Issue by umol-unibas** [chocolatey-community/chocolatey-packages#2351]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

0.79

### Download location

https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.79-installer.msi

### Package Page

https://community.chocolatey.org/packages/putty

**Comment by umol-unibas** [comment]
Could be please update the github-repo considering putty / putty.install? We depend on the latest chocolateyinstall.ps1 script. Are there still any circumstances preventing you / AU-Module from updating this? See [Issue #2291](https://github.com/chocolatey-community/chocolatey-packages/issues/2291) be great! Thank

**Comment by pauby** [comment]
As mentioned in [this comment](https://github.com/chocolatey-community/chocolatey-packages/issues/2291#issuecomment-1701734744) AU started pushing commits again _after_ the approval of the last version of `putty` and `putty.install`. So there have been no changes that would update those scripts since then.

Once a new version of PuTTY is released, the packages will be updated, including the scripts.

As there is nothing more for us to do here, I'll go ahead and close this issue.
