### ISSUE TITLE
(becyicongrabber) projectUrl and licenseUrl need amending as site no longer available

### ISSUE THREAD

**Issue by asheroto** [chocolatey-community/chocolatey-packages#2417]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

2.30.0.20161027

### Current Behaviour

Package URL:
https://community.chocolatey.org/packages/becyicongrabber

Clicking on "Software Site" links to here:
http://www.becyhome.de/download_eng.htm#becyicongrabber

That is dead, shows 404 Not Found...

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/49938263/643f1f02-ee69-4291-99d3-b2ee54542e1a)

The homepage http://www.becyhome.de is also dead. White page, empty HTML document, although HTTP status code 200.

Did a WHOIS lookup but experienced issues, oddly enough.

### Expected Behaviour

Working link.

### Steps To Reproduce

1. Visit package
2. Click `Software Site`

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

**Comment by TheCakeIsNaOH** [comment]
As far as I'm aware, there is not a replacement website, so there is nothing to amend the links to.

The package is embedded and it still works, so there is no reason to unlist the package. 

The package is in the manual folder in this repository, so I'm not seeing any action required for this package.

**Comment by asheroto** [comment]
Understood. I wasn't concerned about delisting so much as someone else taking over the domain of the Software Site, and potentially linking to or providing some malicious or questionable content. More of a head's up than anything. 😊

**Comment by AdmiringWorm** [comment]
> Understood. I wasn't concerned about delisting so much as someone else taking over the domain of the Software Site, and potentially linking to or providing some malicious or questionable content. More of a head's up than anything. 😊

I understand your concern, but unfortunately the only action we can take is to unlist the package. Changing the URLs requires a new fix version of the package, and with the upstream URLs no longer existing and there is nothing that replaces them we cannot create a fix version as the binary file cannot be verified anymore.

Also, since there are no replacement URLs, there isn't anything to change them to either, and the software URL is a required URL for any packages on the Chocolatey Community Repository.

Finally, while we can unlist the package, I am hesitant to do so as the software is still used by other people (myself included).

Due to the above, I'll be closing this issue. But we can always re-open this if the situation changes in the future.
