### ISSUE TITLE
(libreoffice-fresh) v24.2 out for ~1.5 months, v7.6.x is now Still

### ISSUE THREAD

**Issue by Caligatio** [chocolatey-community/chocolatey-packages#2443]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

24.2.1

### Download location

https://download.documentfoundation.org/libreoffice/stable/24.2.1/win/x86_64/LibreOffice_24.2.1_Win_x86-64.msi.mirrorlist

### Package Page

https://community.chocolatey.org/packages/libreoffice-fresh

**Comment by Caligatio** [comment]
Libreoffice switched to a date-based versioning scheme (ish) and launched v24.2 [sometime in late-January/early-February 2024](https://wiki.documentfoundation.org/ReleasePlan/24.2). The first bug fix release, v24.2.1, was released on 29 February 2024.

It appears that v7.6 - which is currently the "Fresh" line on chocolatey - is now considered Stable/Still.

**Comment by TheCakeIsNaOH** [comment]
See the note in the package description:
![image](https://github.com/chocolatey-community/chocolatey-packages/assets/38865330/40585d02-0342-46b8-a805-77811552368e)

The `libreoffice-still` package has been updated to the v6.7.x minor version, as the update service has made it available to those on the still channel/stream. However, I just checked my Libreoffice Fresh installation, and it looks like they have not made the v24.x.y major version available via the update service yet. As it is not available yet via the update service, the package is not out of date, so this issue is not valid for the moment. 

This issue could be reopened if the status changes in the future and the package does not get automatically updated.

**Comment by Caligatio** [comment]
@TheCakeIsNaOH I did notice the disclaimer about the update delay but I figured 1.5 months seemed long enough for the new version to hit the updater.... apparently not :)

**Comment by Caligatio** [comment]
@TheCakeIsNaOH Libreoffice Fresh and Still are now the same version. I unfortunately have no insight into the LibreOffice updater but is it possible they're not offering a direct upgrade path from v7 -> v24?

**Comment by TheCakeIsNaOH** [comment]
> I unfortunately have no insight into the LibreOffice updater but is it possible they're not offering a direct upgrade path from v7 -> v24?

That is something you would have to ask The Document Foundation about (developers of LibreOffice). 

To my understanding, the current package update mechanism was created at their request, as they desired the Chocolatey package not be updated until the version was available on the update api.
