### ISSUE TITLE
(ruby) Request a re-run of verification testing for packages with dependency race condition

### ISSUE THREAD

**Issue by chadlwilson** [chocolatey-community/chocolatey-packages#2465]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

3.3.1.1, 3.2.4.1, 3.1.5.1, 3.0.7.1

### Current Behaviour

These virtual/meta packages seemed to run before `ruby.install` had completed so failed on dependencies and now seem to be stuck. This didn't happen for the last batch of releases, so this seems to be a bit weird.

All `ruby.install` dependencies are now complete and published so I think these just need to be re-submitted for **verification testing** to the queue as-is?

https://community.chocolatey.org/packages/ruby/3.3.1.1
https://community.chocolatey.org/packages/ruby/3.2.4.1
https://community.chocolatey.org/packages/ruby/3.1.5.1
https://community.chocolatey.org/packages/ruby/3.0.7.1

### Expected Behaviour

Packages not "waiting for maintainer" :-)

https://community.chocolatey.org/packages/ruby/3.3.1.1
https://community.chocolatey.org/packages/ruby/3.2.4.1
https://community.chocolatey.org/packages/ruby/3.1.5.1
https://community.chocolatey.org/packages/ruby/3.0.7.1

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A - but see https://gist.github.com/choco-bot/8c259be3c582547fc3ac106804e7b744
```

**Comment by chadlwilson** [comment]
My bad, this seems to have fixed itself.

**Comment by AdmiringWorm** [comment]
As there hadn't been a response here, I figured I'd post something about it here.

Huge thanks to the moderators, as they are the ones that triggered a re-run of the Ruby package versions you mentioned.

A small update on the issue as well, this issue wasn't common before due to a bug on the Chocolatey Community Repository that was fixed a few weeks ago, and we have additional work planned to make it so a triggering a re-run of meta packages won't be needed in the future. This is, however, still a bit away, so I/we would appreciate it to be notified about these issues.

Either here as an issue/discussion, or through discord at https://ch0.co/community (channel `community-maintainers` or `community-repository` would probably be the best).
