### ISSUE TITLE
libreoffice-fresh

### ISSUE THREAD

**Issue by gradogirl** [chocolatey-community/chocolatey-packages#2466]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

24.2.1

### Download location

https://www.libreoffice.org/donate/dl/win-x86_64/24.2.3/en-US/LibreOffice_24.2.3_Win_x86-64.msi

### Package Page

https://community.chocolatey.org/packages/libreoffice-fresh

**Comment by zWhdmB5T** [comment]
- [Release Plan 24.2](https://wiki.documentfoundation.org/ReleasePlan/24.2)
- [Release Notes](https://www.libreoffice.org/download/release-notes/)

[general.useragent.override="LibreOffice 0 (b6c8ba5-8c0b455-0b5e650-d7f0dd3-b100c87; Chocolatey; x86;")](https://update.libreoffice.org/check.php)
```
<inst:description xmlns:inst="http://update.libreoffice.org/description">
  <inst:id>LibreOffice 24.2.2</inst:id>
  <inst:gitid>d56cc158d8a96260b836f100ef4b4ef25d6f1a01</inst:gitid>
  <inst:os>Chocolatey</inst:os>
  <inst:arch>x86</inst:arch>
  <inst:version>24.2.2</inst:version>
  <inst:buildid>9999</inst:buildid>
  <inst:update type="text/html" src="https://www.libreoffice.org/download/download/?lang=de&amp;version=24.2.2&amp;pk_campaign=update"/>
</inst:description>
```

**Comment by pauby** [comment]
@zWhdmB5T can you clarify what you're providing here as there is no context.

**Comment by zWhdmB5T** [comment]
> @zWhdmB5T can you clarify what you're providing here as there is no context.

I provided details (release notes and other) for the current LibreOffice, i.e. Fresh.

Maybe, since the [new versioning scheme since 7.6 -> 24.2](https://wiki.documentfoundation.org/ReleasePlan), scripts are not working correctly, any more.

I state this, because when you check the LibreOffice version update check [general.useragent.override="LibreOffice 0 (b6c8ba5-8c0b455-0b5e650-d7f0dd3-b100c87; Chocolatey; x86; )"](https://update.libreoffice.org/check.php), it's already at 24.2.2 (please, see above), i.e. the 24.2 path — but Chocolatey still says [7.6.5](https://community.chocolatey.org/packages/libreoffice-fresh#versionhistory), i.e. the 7.6 path. This specific version for Fresh (7.6.5) is even lower than the version for Still which is [7.6.6](https://community.chocolatey.org/packages/libreoffice-still#versionhistory) (i.e. the 7.6 path too, that is correct for Still — but Fresh has to be the 24.2 path).

**Comment by pauby** [comment]
@zWhdmB5T I appreciate you provided those details, but it wasn't clear to me what they were for, what you were trying to say. You provided some XML, a couple of links and that was it. There was no _context_.

Thank you for providing that context.

**Comment by TheCakeIsNaOH** [comment]
It looks like the update service made the version available to the CI machine, as the package was updated to v24.2.3 and is now available on the Community Repository:
https://community.chocolatey.org/packages/libreoffice-fresh/24.2.3
