### ISSUE TITLE
git

### ISSUE THREAD

**Issue by felfert** [chocolatey-community/chocolatey-packages#2554]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

2.47.0

### Current Behaviour

There is a bug in upstream, breaking fetch on some repositories. See [issue at github](https://github.com/git-for-windows/git/issues/5207).
So: Please retract the 2.47.0 release (2.46.2 works fine)

### Expected Behaviour

See upstream issue.

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

**Comment by corbob** [comment]
Thank you for reporting this. We've added a comment to the Disqus comments on the page. As upstream has not pulled the release, we are unlikely to unlist it. Typically we would only unlist a package if the upstream package was also unlisted or removed for some reason.

Since the upstream is still available, I'm going to close this issue. We can reopen it should the upstream situation change.
