### ISSUE TITLE
(git) outdated, critical regression fixed in v2.47.0.windows.2

### ISSUE THREAD

**Issue by here-abarany** [chocolatey-community/chocolatey-packages#2558]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

v2.47.0.windows.2

### Download location

https://github.com/git-for-windows/git/releases/tag/v2.47.0.windows.2

### Package Page

https://community.chocolatey.org/packages/git

**Comment by here-abarany** [comment]
See also: #2554 for the regression, the decision was to not pull the Chocolatey release since the upstream release was pulled. According to #2102 there might be some issues with the version number parsing, since the ".windows.x" version suffix is added to releases specific to Git for Windows as opposed to the upstream Git version. However, this is a critical regression that makes git largely unusable if you rely on SSH, so *some* action is needed I think.

**Comment by AdmiringWorm** [comment]
> According to https://github.com/chocolatey-community/chocolatey-packages/issues/2102 there might be some issues with the version number parsing, since the ".windows.x" version suffix is added to releases specific to Git for Windows as opposed to the upstream Git version.

You are correct, due to how only the part of the version before `windows` is detected as part of the version number, and whenever the installer itself changes outside the version number, we need to create a manual fix version of the packages. I did consider fixing this in the past, but I opted to not fix it at the time so we can control the package using the proper versions when possible (the number after the word `windows` is not part of the version, but rather the revision).

> However, this is a critical regression that makes git largely unusable if you rely on SSH, so some action is needed I think.

I agree, this does warrant a new fix version of the package being created. I'll take a look at creating a fix version, but that may not happen until tomorrow or during the weekend unfortunately.

**Comment by AdmiringWorm** [comment]
The git packages have been queued to have a fix version created and pushed to the community repository now.

It should show up in a few hours during normal installation (if all goes well).

**Comment by here-abarany** [comment]
Thanks, it doesn't seem to show up yet when running `choco upgrade`, but using `choco install` with the version explicitly set I was able to get the latest version and verified that it works as expected.

**Comment by AdmiringWorm** [comment]
> Thanks, it doesn't seem to show up yet when running `choco upgrade`, but using `choco install` with the version explicitly set I was able to get the latest version and verified that it works as expected.

Most likely that was because it had not been approved yet on Chocolatey Community Repository (or it could be a caching issue). Using an explicit version to bypass that is generally not recommended, as until the package has been approved it is not considered immutable and may change before it is approved.
